SKILL_LEVELS = {
    20: "divine",
    19: "utopian",
    18: "magical",
    17: "mythical",
    16: "extra-terrestrial",
    15: "titanic",
    14: "supernatural",
    13: "world class",
    12: "magnificent",
    11: "brilliant",
    10: "outstanding",
    9: "formidable",
    8: "excellent",
    7: "solid",
    6: "passable",
    5: "inadequate",
    4: "weak",
    3: "poor",
    2: "wretched",
    1: "disastrous",
    0: "non-existent",
}
